### ISSUE TITLE
Receiving a SegmentationFault after calling view.Present For Android

### ISSUE THREAD

**Issue by RFS-6ro** [adaptyteam/AdaptyUI-Unity#2]
![image](https://github.com/adaptyteam/AdaptyUI-Unity/assets/56915388/508a4ab6-7490-4da4-b374-2df5c241b5e5)

Here's the code I use to show the paywall:
It appears for one second and the application crashes.

```csharp
#region Fetch
Adapty.GetPaywall
(
    placement.ToString(), 
    (paywall, error) => 
    {
        if(error == null) return:
        
        #region Create Paywall View
        AdaptyUI.CreatePaywallView
        (
            paywall, "en", preloadProducts: true, 
            (view, error) => 
            {
                  if(error == null)  return:
                  
                  #region Present Paywall View
                  
                  view.Present((error) => { }); //Error is null
                  
                  #endregion
              }
          );
          #endregion
    }
);
#endregion
```

**Comment by fablerq** [comment]
+1 for the same behavior

**Comment by RFS-6ro** [comment]
Attaching Crash Log captured on android device through Android Logcat

[Adapty_SIGSEGV_Crash_Log.txt](https://github.com/adaptyteam/AdaptyUI-Unity/files/14818972/Adapty_SIGSEGV_Crash_Log.txt)

**Comment by vladd-g** [comment]
@RFS-6ro @fablerq thank you for the report! Could you please check if [this solution](https://forum.unity.com/threads/fatal-signal-11-sigsegv-code-1-segv_maperr-fault-addr-0x0.1427019/#post-9200708) fixes the problem?

**Comment by RFS-6ro** [comment]
> @RFS-6ro @fablerq thank you for the report! Could you please check if [this solution](https://forum.unity.com/threads/fatal-signal-11-sigsegv-code-1-segv_maperr-fault-addr-0x0.1427019/#post-9200708) fixes the problem?

I was using il2cpp even before integrating your solution

**Comment by vladd-g** [comment]
@RFS-6ro which Adapty and Unity versions do you use?

**Comment by RFS-6ro** [comment]
@vladd-g 
Unity v2022.3.8f1
AdaptySDK v2.7.1 (Yes, you said to use 2.7.0, but it's not compatible due to compilation errors (missing `Adapty.SetUnknownEventListener` method))
Adapty.UI v2.0.1

**Comment by vladd-g** [comment]
@RFS-6ro thank you!

We built with 2021.3.30f1, it was ok

Is it the same for AdaptyUI v2.0.0?

**Comment by RFS-6ro** [comment]
@vladd-g Will try your sample project and those versions right away

**Comment by RFS-6ro** [comment]
Ok, I figured it out. The problem was with Sentry SDK that is monitoring activities and unity sessions.
Since Adapty is pausing Unity activity and creating its own - Sentry was throwing an exception, closing an application.
